services:
  box3:
    image: alpine
    container_name: Box3
    command: sleep 3600
  box4:
    image: alpine
    container_name: Box4
    command: sleep 3600
  db:
    image: mysql
    container_name: MySQLDB2
    ports:
      - 3312:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    volumes:
      - mysqlsuperdb:/var/lib/mysql

volumes:
  mysqlsuperdb:
