name: Docker Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p "${{ secrets.DOCKER_PASSWORD }}"

      - name: Construir imagen
        run: docker build -t luisferlcc/nodetest:latest .

      - name: Publicar en Docker Hub
        run: docker push luisferlcc/nodetest:latest
